version: '3.7'

services:
  db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql/

  web:
    build: ./web
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./web/:/usr/src/app/
    depends_on:
      - db

volumes:
  mariadb_data:
