version: '3.1'

services:
  db:
    image: mariadb
    env_file:
      - .env.db
    volumes:
    - mariadb_data:/var/lib/mysql/

  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    env_file:
      - .env.db
      - .env
    ports:
    - 5000:5000
    volumes:
    - ./web/:/usr/src/app/
    depends_on:
      - db

volumes:
  mariadb_data: