version: '3.1'

services:

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
     - 5000:5000

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./dbconfig:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: mysqladmin ping -h localhost -p${DB_ROOT_PASSWORD}
      interval: 1s
      retries: 20
