version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: WebApp
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-entrypoint:/docker-entrypoint-initdb.d:ro

  web:
    build: ./web
    env_file:
      - .env
    volumes:
      - ./web:/usr/src/web
    ports:
    - 5000:5000
    depends_on:
      - db




